
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.MötesFörslag;
import models.User;
import repository.MeetingRepository;
import repository.UserRepository;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jenniferhuang
 */
public class Mötesförfrågning extends javax.swing.JFrame {
    private UserRepository userRepository;
    private MeetingRepository meetingRepository;
    private String inloggadPerson;
    private Integer userId;
    
    private List<MötesFörslag> mötesFörslagFörAnvändare = new ArrayList();
    
     
     
    public Mötesförfrågning(String anvandarnamn) {
        initComponents();
        userRepository = new UserRepository();
        meetingRepository = new MeetingRepository();
        inloggadPerson = anvandarnamn;
        getUserId(anvandarnamn);
        hämtaMötesFörslag(userId);
        läggTillMötesFörslagTillCombobox();
    }
    
    private void getUserId(String anvandarnamn) {
         userId = userRepository.getUserIdForUsernamn(anvandarnamn);
    }
    
    private void hämtaMötesFörslag(Integer userId) {
        mötesFörslagFörAnvändare = meetingRepository.getMeetingsForUser(userId);
    }
    
    private void läggTillMötesFörslagTillCombobox() {
        for(MötesFörslag förslag : mötesFörslagFörAnvändare) {
            mötesCombobox.addItem(förslag);
        }
    }
    
    private void läggTillFörslagsTider(MötesFörslag förslag) {
        tidFörslagsCombobox.removeAllItems();
        tidFörslagsCombobox.addItem(förslag.getFörslag1());
        tidFörslagsCombobox.addItem(förslag.getFörslag2());
        tidFörslagsCombobox.addItem(förslag.getFörslag3());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MötesförfrågningLbl = new javax.swing.JLabel();
        minaSidorBtn = new javax.swing.JButton();
        tidFörslagsCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mötesCombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MötesförfrågningLbl.setText("Mötesförfrågning");
        MötesförfrågningLbl.setAlignmentY(2.0F);

        minaSidorBtn.setText("Mina sidor");
        minaSidorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minaSidorBtnActionPerformed(evt);
            }
        });

        tidFörslagsCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidFörslagsComboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Tidsförslag");

        jButton1.setText("Bekräfta tid");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mötesCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mötesComboboxActionPerformed(evt);
            }
        });

        jLabel2.setText("Titel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(MötesförfrågningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minaSidorBtn))
                            .addComponent(mötesCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tidFörslagsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MötesförfrågningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mötesCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidFörslagsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(minaSidorBtn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minaSidorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minaSidorBtnActionPerformed
        try {
            String anvandarnamn = inloggadPerson;
            MinaSidor start = new MinaSidor(anvandarnamn);
            start.setVisible(true);
            Mötesförfrågning.this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Mötesförfrågning.class.getName()).log(Level.SEVERE, null, ex);
        }
                
              
    }//GEN-LAST:event_minaSidorBtnActionPerformed

    private void tidFörslagsComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidFörslagsComboboxActionPerformed
        
    }//GEN-LAST:event_tidFörslagsComboboxActionPerformed

    private void mötesComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mötesComboboxActionPerformed
        MötesFörslag valtFörslag = (MötesFörslag)mötesCombobox.getSelectedItem();
        läggTillFörslagsTider(valtFörslag);
    }//GEN-LAST:event_mötesComboboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LocalDateTime bekräftadTid = (LocalDateTime)tidFörslagsCombobox.getSelectedItem();
        MötesFörslag förslag = (MötesFörslag)mötesCombobox.getSelectedItem();
        
        boolean lyckad = meetingRepository.bekräftaMöteFörAnvändare(förslag.getMötesFk(), userId, bekräftadTid);
        if(lyckad) {
            JOptionPane.showMessageDialog(null, "Du har bekräftat tiden: " + bekräftadTid + " för mötet: " + förslag.getMötesTitel());
        } else {
            JOptionPane.showMessageDialog(null, "Misslyckat");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mötesförfrågning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mötesförfrågning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mötesförfrågning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mötesförfrågning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mötesförfrågning("jenniferhuang").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MötesförfrågningLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton minaSidorBtn;
    private javax.swing.JComboBox<MötesFörslag> mötesCombobox;
    private javax.swing.JComboBox<LocalDateTime> tidFörslagsCombobox;
    // End of variables declaration//GEN-END:variables

}
